#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 29 15:45:17 CEST 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 99b487eb9d534c198c4054a3b6ad2863 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Computer_behav xil_defaultlib.Computer -log elaborate.log"
xelab -wto 99b487eb9d534c198c4054a3b6ad2863 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot Computer_behav xil_defaultlib.Computer -log elaborate.log

